### [정상] 리소스를 생성한다.
POST http://localhost:8080/resource
Content-Type: application/json

{
  "cpu": 1,
  "memory": 1,
  "userName": "testName",
  "serverId": 1
}

### [비정상] 리소스를 1개 미만으로 요청하면 에러가 발생한다.
POST http://localhost:8080/resource?cpu=1&memory=0
Content-Type: application/json

{
  "cpu": 0,
  "memory": 1,
  "userName": "testName",
  "serverId": 1
}
