create table server_resource (
    created_datetime timestamp(6) default current_timestamp,
    id bigint generated by default as identity,
    name varchar(255),
    total_cpu bigint not null,
    total_memory bigint not null,
    update_datetime timestamp(6),
    used_cpu bigint default 0 not null,
    used_memory bigint default 0 not null,
    version bigint default 0 not null,
    primary key (id)
);

create table user_resource (
    id bigint generated by default as identity,
    server_resource_id bigint,
    used_cpu bigint not null,
    used_memory bigint not null,
    user_id bigint,
    update_datetime timestamp(6),
    created_datetime timestamp(6) default current_timestamp,
    primary key (id)
);

create table users (
   created_datetime timestamp(6) default current_timestamp,
   id bigint generated by default as identity,
   update_datetime timestamp(6),
   name varchar(255) unique,
   primary key (id)
);

alter table if exists user_resource
    add constraint FKgwhp546fckqpq9kx0uf60vtoh
    foreign key (server_resource_id)
    references server_resource;

alter table if exists user_resource
    add constraint FKarpq9iuy8kjdtjysjf68gdi50
    foreign key (user_id)
    references users;
